POST http://localhost:3333/goals
Content-Type: application/json

{
  "title": "Jiu Jitsu",
  "desiredWeeklyFrequency": 4
}

###

GET http://localhost:3333/pending-goals

###

GET http://localhost:3333/summary